### ISSUE TITLE
Do you have a plan to support Immutable.js?

### ISSUE THREAD

**Issue by zetoke** [yesmeck/tuku#3]
Hello!
I looked up at this project and I like it at first look 😄 
It very close to what I want to build/create for my own purpose as experiment!

Do you have any plans to support Immutable.js?

( sorry for my bad english ^_^ )

**Comment by yesmeck** [comment]
Yep, it is on my todo list.

**Comment by yesmeck** [comment]
Hi @zetoke, seems like Feeble supports Immutable.js out of box 😱 , I just played Immutable.js with the [hackernews](https://github.com/feeblejs/hackernews/commit/5b36d5de3688ddce09f799a38eb0ac21f0085005) demo, it works without any problems.

**Comment by zetoke** [comment]
Oh wow. That's cool! 
For my custom vanilla redux project I commonly use redux-immutable as custom combineReducers.
